baseURL: https://www.8cribble.com/
languageCode: en-us
title: Infinite Scribble, LLC
theme: hugo-theme-cleanwhite
outputs:
  home:
    - HTML
    - RSS
params:
  header_image: img/forest.jpg
  SEOTitle: Infinite Scribble
  description: Games and apps for the discerning user.
  keyword: >-
    Games, Puzzles, iOS
  slogan: Puzzling Products
  image_404: img/404-bg.jpg
  title_404: 'Page not found'
  omit_categories: false
  page_view_conter: false
  leancloud_app_id: ''
  leancloud_app_key: ''
  algolia_search: false
  sidebar_about_description: 'Software Developer, Engineering Manager, Curious Character'
  sidebar_avatar: img/graham.png
  featured_tags: true
  featured_condition_size: 1
  ba_track_id: ''
  disqus_proxy: ''
  disqus_site: ''
  twikoo_env_id: ''
  reward: false
  friends: true
  bookmarks: false
  about_me: true
  googleAnalytics: 'UA-67535606-1'
  social:
    rss: true
    github: 'https://github.com/8cribble'
    twitter: 'https://twitter.com/8cribble'
  addtional_menus:
    - title: ARCHIVE
      href: /top/archive/
    - title: ABOUT
      href: /top/about/
markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
